name: transformable
description: Transformable creates a 2D scrollable and scalable Flutter widget.

author: Matthew Cliatt <matthewcliatt@gmail.com>
homepage: https://github.com/mtcliatt/transformable
repository: https://github.com/mtcliatt/transformable

version: 1.1.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
